# ğŸ›  Configuration file for NR-SLD-Chi Predictor
# Modify these settings according to your project structure.

root: .

### âš™ï¸ SLD-Chi settings ###
sld_predict_chi:
    file:
        model_experimental_sld_profile: data/mod_expt.npy # ğŸ“‰ Experimental SLD profile data file (for Chi Prediction)
        model_sld_file: data/mod_sld_fp49.npy # ğŸ“‰ SLD Profile file (input for training)
        model_chi_params_file: data/mod_params_fp49.npy # ğŸ“‰ Chi Parameters file (input label for training)
    
    models:
        latent_dim: 2  # Dimension for latent space
        batch_size: 16  # Batch size for training
        ae_epochs: 20  # Autoencoder training epochs
        mlp_epochs: 20  # MLP training epochs

### âš™ï¸ NR-SLD profile settings ###
nr_predict_sld:
    file:
        nr_train: data/curves/nr_train.npy   #Generated nr curves for training
        sld_train: data/curves/sld_train.npy    #Generated sld curves for training
        
    models:
        model: data/trained_nr_sld_model.pth # Path to save and load the CNN model
        num_film_layers: 5  # Number of film layers to generate the simulated physical model
        num_curves: 50000   # Number of generated curves for training 
        epochs: 10 # CNN training epochs
        batch_size: 32 # Batch size for training
        layers: 12 # model layers
        dropout: 0.5 # Dropout rate for training
        normalization_stats: data/normalization_stat.npy   #Normalization statistics
